# 1. Libraries

In [1]:
import pandas as pd
import numpy as np
import glob
import os
from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd
import os
import seaborn as sns

sns.set_style("whitegrid")

# 2. Data Path and Loading

In [2]:
DATA_DIR = Path("../data/body_tracking")

In [3]:
participant_id = "001"

In [4]:
dfs = []

for condition in [1, 2, 3]:
    matches = list(DATA_DIR.glob(f"{participant_id}_BT_Data_Condition{condition}_*.csv"))

    if not matches:
        raise FileNotFoundError(
            f"No file found for participant {participant_id}, condition {condition}"
        )

    file_path = matches[0]

    df_condition = pd.read_csv(file_path, low_memory=False)
    df_condition["participant_id"] = participant_id
    df_condition["condition_number"] = condition

    dfs.append(df_condition)

df = pd.concat(dfs, ignore_index=True)
df.head()

,raw_timestamp,relative_to_unix_epoch_timestamp,RightFoot_pos_x,RightFoot_pos_y,RightFoot_pos_z,RightFoot_rot_x,RightFoot_rot_y,RightFoot_rot_z,RightFoot_rot_w,LeftFoot_pos_x,...,RightGrab_obj_pos_z,RightGrab_obj_rot_x,RightGrab_obj_rot_y,RightGrab_obj_rot_z,RightGrab_obj_rot_w,model_name,model_rot_deg,LeftFootArea,RightFootArea,participant_id
0,1778060264386,592.3813,0.506676,0.095329,-0.342568,0.818095,0.274210,0.324857,-0.387294,0.465868,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
1,1778060264403,592.3813,0.506538,0.095583,-0.342396,0.818017,0.273979,0.324857,-0.387625,0.465795,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
2,1778060264407,592.4013,0.506474,0.095584,-0.342417,0.818036,0.273922,0.324878,-0.387605,0.465859,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
3,1778060264419,592.4128,0.506497,0.095531,-0.342456,0.818053,0.273932,0.324833,-0.387601,0.465807,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
4,1778060264430,592.4241,0.506437,0.095419,-0.342522,0.817992,0.273856,0.324953,-0.387682,0.465771,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001

In [5]:
df

,raw_timestamp,relative_to_unix_epoch_timestamp,RightFoot_pos_x,RightFoot_pos_y,RightFoot_pos_z,RightFoot_rot_x,RightFoot_rot_y,RightFoot_rot_z,RightFoot_rot_w,LeftFoot_pos_x,...,RightGrab_obj_pos_z,RightGrab_obj_rot_x,RightGrab_obj_rot_y,RightGrab_obj_rot_z,RightGrab_obj_rot_w,model_name,model_rot_deg,LeftFootArea,RightFootArea,participant_id
0,1778060264386,592.3813,0.506676,0.095329,-0.342568,0.818095,0.274210,0.324857,-0.387294,0.465868,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
1,1778060264403,592.3813,0.506538,0.095583,-0.342396,0.818017,0.273979,0.324857,-0.387625,0.465795,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
2,1778060264407,592.4013,0.506474,0.095584,-0.342417,0.818036,0.273922,0.324878,-0.387605,0.465859,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
3,1778060264419,592.4128,0.506497,0.095531,-0.342456,0.818053,0.273932,0.324833,-0.387601,0.465807,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
4,1778060264430,592.4241,0.506437,0.095419,-0.342522,0.817992,0.273856,0.324953,-0.387682,0.465771,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322391,1778063893668,3746.4340,0.357159,0.095378,-0.180606,0.734597,0.346274,0.480469,-0.331075,0.419986,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
322392,1778063893679,3746.4450,0.357132,0.095412,-0.180687,0.734658,0.346235,0.480462,-0.330990,0.419960,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
322393,1778063893690,3746.4560,0.357133,0.095380,-0.180702,0.734526,0.346242,0.480537,-0.331168,0.419906,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
322394,1778063893701,3746.4670,0.357178,0.095381,-0.180782,0.734589,0.346298,0.480496,-0.331028,0.419965,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
322395,1778063893712,3746.4780,0.357159,0.095477,-0.180684,0.734668,0.346339,0.480364,-0.331002,0.419930,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001

In [6]:
df.head()

,raw_timestamp,relative_to_unix_epoch_timestamp,RightFoot_pos_x,RightFoot_pos_y,RightFoot_pos_z,RightFoot_rot_x,RightFoot_rot_y,RightFoot_rot_z,RightFoot_rot_w,LeftFoot_pos_x,...,RightGrab_obj_pos_z,RightGrab_obj_rot_x,RightGrab_obj_rot_y,RightGrab_obj_rot_z,RightGrab_obj_rot_w,model_name,model_rot_deg,LeftFootArea,RightFootArea,participant_id
0,1778060264386,592.3813,0.506676,0.095329,-0.342568,0.818095,0.274210,0.324857,-0.387294,0.465868,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
1,1778060264403,592.3813,0.506538,0.095583,-0.342396,0.818017,0.273979,0.324857,-0.387625,0.465795,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
2,1778060264407,592.4013,0.506474,0.095584,-0.342417,0.818036,0.273922,0.324878,-0.387605,0.465859,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
3,1778060264419,592.4128,0.506497,0.095531,-0.342456,0.818053,0.273932,0.324833,-0.387601,0.465807,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001
4,1778060264430,592.4241,0.506437,0.095419,-0.342522,0.817992,0.273856,0.324953,-0.387682,0.465771,...,0.0,0.0,0.0,0.0,1.0,NaN,0,Work,Work,001

In [6]:
df["LeftHand_grabbed_name"].value_counts()

LeftHand_grabbed_name
ValidationButtonLeft        8510
Lego_1x3_Pink (1)           3616
brick_2x2_yellow_res_073    2666
brick_2x2_yellow_res_109    2045
work_desk_base              1848
                            ...
Lego_4x2_Pink_Dis              2
Lego_Board_10x10               2
brick_2x4_blue_dis_014         1
brick_2x4_yellow_res_066       1
brick_2x3_green_dis_022        1
Name: count, Length: 98, dtype: int64

In [8]:
df["RightHand_grabbed_name"].value_counts()

RightHand_grabbed_name
ValidationButtonRight      8658
Lego_1x3_Green             2450
work_desk_base             2401
brick_2x2_pink_res_115     2358
brick_2x4_blue_res_068     1909
                           ...
brick_2x2_pink_res_013        6
brick_2x4_green_res_117       5
resource_desk_base            3
brick_1x3_blue_dis_057        1
QuestionButton7               1
Name: count, Length: 120, dtype: int64